[package]
name = "readme-gen"
version = "0.1.0"
edition = "2024"

[dependencies]
walkdir = "2"
toml = "0.8.20"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
quick-xml = "0.37.4"